version: 2

sources:
  - name: covid      # dbt source name
    database: pc_dbt_db_raw_date          #  Add this line
    schema: public                 # Schema in your Snowflake database
    tables:
      - name: jhu_vaccines
        description: "Table containing COVID-19 vaccination data."
      - name: ct_us_covid_tests
        description: "Table containing COVID-19 test results by date."
        
